export const URL = 'http://localhost:4000';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

export const POST_SIGNUP = 'POST_SIGNUP';
export const POST_SIGNUP_ERROR = 'POST_SIGNUP_ERROR';

export const GET_USER_PRODUCTS = 'GET_USER_PRODUCTS';
export const GET_USER_PRODUCTS_ERROR = 'GET_USER_PRODUCTS_ERROR';

export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';
export const GET_USER_COMMENTS_ERROR = 'GET_USER_COMMENTS_ERROR';

export const GET_USER_BOOKMARKS = 'GET_USER_BOOKMARKS';
export const GET_USER_BOOKMARKS_ERROR = 'GET_USER_BOOKMARKS_ERROR';

export const GET_USER_OFFERS = 'GET_USER_OFFERS';
export const GET_USER_OFFERS_ERROR = 'GET_USER_OFFERS_ERROR';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_ERROR = 'GET_PRODUCT_DETAILS_ERROR';

export const GET_PRODUCT_COMMENTS = 'GET_PRODUCT_COMMENTS';
export const GET_PRODUCT_COMMENTS_ERROR = 'GET_PRODUCT_COMMENTS_ERROR';

export const POST_BOOKMARKS = 'POST_BOOKMARKS';
export const POST_BOOKMARKS_ERROR = 'POST_BOOKMARKS_ERROR';

export const POST_COMMENTS = 'POST_COMMENTS';
export const POST_COMMENTS_ERROR = 'POST_COMMENTS_ERROR';

export const POST_OFFERS = 'POST_OFFERS';
export const POST_OFFERS_ERROR = 'POST_OFFERS_ERRORS';

export const RESET_STORE = 'RESET_STORE';